# -*- coding: utf-8 -*-
"""cog3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pCnJa0-fYlYPKSMrXtQHyWWRTvrfmBKI
"""

#Q1
import pandas as pd

data = {
    "Tid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Refund": ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No"],
    "Marital Status": [
        "Single", "Married", "Single", "Married", "Divorced",
        "Married", "Divorced", "Single", "Married", "Single"
    ],
    "Taxable Income": [
        "125K", "100K", "70K", "120K", "95K",
        "60K", "220K", "85K", "75K", "90K"
    ],
    "Cheat": ["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"]
}

df = pd.DataFrame(data)

print(df)

#Q2
df.loc[[0,4,7,8]]

#Q3.1
df.loc[3:7]

#Q3.2
df.iloc[4:9, 2:5]

#Q3.3
df.iloc[:, 1:4]

#Q4
import kagglehub
import pandas as pd

path = kagglehub.dataset_download("uciml/iris")
print("Path to dataset files:", path)

file_path = path + '/Iris.csv'

iris_df = pd.read_csv(file_path)
print(iris_df.head())

#Q5
iris_df = pd.read_csv(file_path)

iris_df = iris_df.drop(index=4)
iris_df = iris_df.drop(iris_df.columns[3], axis=1)

print(iris_df.head())

#Q6
import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-06-01", "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}

employees_df = pd.DataFrame(data)
employees_df.to_csv("employees.csv", index=False)

df = pd.read_csv("employees.csv")
print(df)

#Q6.a
print(employees_df.shape)

#Q6.b
print(employees_df.info())

#Q6.c
print(employees_df.describe())

#Q6.d
print("first 5 rows:")
print(employees_df.head(5))

print("last 3 rows:")
print(employees_df.tail(3))

#Q6.e.i
avg_salary=employees_df["Salary"].mean()
print("Average salary =",avg_salary)

#Q6.e.ii
total_bonus=employees_df["Bonus"].sum()
print("Total bonus =",total_bonus)

#Q6.e.iii
average_exp=employees_df["Years_of_Experience"].mean()
print("Average Experience =",average_exp)

#Q6.e.iv
highest_rating=employees_df["Rating"].max()
print("Highest rating =",highest_rating)

#Q6.f
sorted_df=employees_df.sort_values(by="Salary",ascending=False)
print(sorted_df)

#Q6.g
def performance(rating):
  if rating>=4.5:
    return "Excellent"
  elif rating>=4.0:
    return "Good"
  else :
    return "Average"

employees_df["Performance"]=employees_df["Rating"].apply(performance)
print(employees_df[["Name","Rating","Performance"]])

#Q6.h
print(employees_df.isnull().sum())

#Q6.i
employees_df.rename(columns={"Employee_ID": "ID"}, inplace=True)

print(df.columns)

#Q6.j.i
experienced=employees_df[employees_df["Years_of_Experience"]>5]
print(experienced["Name"])

#Q6.j.ii
it_employees = employees_df[employees_df["Department"] == "IT"]
print(it_employees["Name"])

#Q6.k
employees_df["Tax"]=employees_df["Salary"]*0.10
print(employees_df)

#Q6.l
employees_df.to_csv("employees_modified.csv",index=False)
print("Modified dataset saved successfully")