# -*- coding: utf-8 -*-
"""cognitive_lab_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rkS4NlQs9FNhNwgi-skhOJz6xXjY7Ecb
"""

roll_no = 1024170139


L = [int(i)*10 for i in str(roll_no)]

print("Original List:", L)


# append()
L.append(50)
print("After append:", L)



# insert()
L.insert(3, 25)
print("After insert:", L)



# remove()
L.remove(0)
print("After remove:", L)



# pop()
L.pop()
print("After pop:", L)



# Sorting
L.sort()
print("Ascending:", L)

L.sort(reverse=True)
print("Descending:", L)


# Slicing
print("First three:", L[:3])
print("Last three:", L[-3:])


# Elements greater than average
avg = sum(L)/len(L)

new_list = [x for x in L if x > avg]

print("Greater than average:", new_list)

scores = tuple(L[:8])

print(scores)



maximum = max(scores)
print("Highest:", maximum)
print("Index:", scores.index(maximum))



minimum = min(scores)
print("Lowest:", minimum)
print("Frequency:", scores.count(minimum))



reverse_list = list(scores[::-1])

print(reverse_list)






x = int(input("Enter score: "))

if x in scores:
    print("Index:", scores.index(x))
    else:
        print("Score not present")





        scores[0] = 100









        first, second, *remaining = scores

        print(first)
        print(second)
        print(remaining)

import random


random.seed(1024170139)


numbers = [random.randint(100,900) for i in range(100)]

print(numbers)


#odd numbers
odd = [x for x in numbers if x%2!=0]

print("Odd count:",len(odd))
print(odd)

#even numbers

even = [x for x in numbers if x%2==0]

print("Even count:",len(even))
print(even)

#function for prime

def is_prime(n):

      if n<2:
        return False

      for i in range(2,int(n**0.5)+1):
        if n%i==0:
            return False

      return True



prime = [x for x in numbers if is_prime(x)]

print("Prime count:",len(prime))
print("Prime numbers:",prime)

#most frequent number
frequency = {}

for x in numbers:
    frequency[x] = frequency.get(x,0)+1


    most_common = max(frequency,key=frequency.get)

    print("Most frequent:",most_common)
    print("Frequency:",frequency[most_common])

digits = [int(i) for i in str(1024170139)]


A = {x*7 for x in digits}

B = {x*9 for x in digits}


print("Set A:",A)
print("Set B:",B)

#union
print("Union:",A.union(B))
#inter
print("Intersection:",A.intersection(B))
#difference

print("A-B:",A.difference(B))

print("B-A:",B.difference(A))
#sym difference
print("Symmetric difference:",
      A.symmetric_difference(B))
#subset and superset
print(A.issubset(B))

print(B.issuperset(A))
#discard()
x=int(input("Enter value to remove: "))

A.discard(x)

print(A)

my_dict = {

  "name":"Sparsh",

  "roll_no":"1024170139",

  "branch":"CSE",

  "age":20,

  "city":"Delhi"

  }

#rename city to location
my_dict["location"] = my_dict.pop("city")
#add cgpa
my_dict["cgpa"] = 9.20
#increase age

my_dict["age"] += 1


print(my_dict)

#delete branch using pop
dict1 = my_dict.copy()

removed = dict1.pop("branch")

print(dict1)
#delete branch using del
dict2 = my_dict.copy()

del dict2["branch"]

print(dict2)
#items
for key,value in my_dict.items():

      print(key,"→",value)

#checking email
if "email" in my_dict:

      print(my_dict["email"])

else:

      print("Email not found")

#friend dic
friend_dict = {

  "name":"Rahul",

  "roll_no":"123456",

  "branch":"ECE",

  "age":20,

  "city":"Mumbai"

  }


  merged = {**my_dict, **friend_dict}


  print(merged)
#dictionery compre
string_dict = {

  k:v for k,v in my_dict.items()

  if isinstance(v,str)

  }


  print(string_dict)